ReservationSystem/Controllers/MasterReservationController.cs
using ReservationSystem.Database;
using ReservationSystem.Entities;
using ReservationSystem.Services;
using ReservationSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReservationSystem.Controllers
{
    public class MasterReservationController : Controller
    {
        // GET: MasterReservation
        bool role = false;
        public void CheckRole()
        {
            role = false;
            if (Session["UserName"] == null)
            {
                role = false;
            }
            string[] roles = System.Web.Security.Roles.GetRolesForUser(Convert.ToString(Session["UserName"]));
            if (roles[0] == "Admin")
            {
                role = true;

            }
        }

        
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Create(int ID)
        {
            EditReservationViewModel model = new EditReservationViewModel();
            model.Room = RoomsService.Instance.GetRoomWithSpecs(ID);
            if (model.Room.HaveWifi == false)
            {
                ViewBag.havewifi = "No";
            }
            else
            {
                ViewBag.havewifi = "Yes";
            }
            return PartialView(model.Room);

        }




        [HttpPost]
        public ActionResult Create(NewReservationViewModel model)
        {
            var newReservation = new Reservations();
            newReservation.ReservationTime = model.ReservationTime;
            newReservation.ReservationAgenda = model.ReservationAgenda;
            newReservation.BookedBy = model.BookedBy;
            newReservation.VacantBy = model.VacantBy;
            newReservation.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(model.RoomSpecificationID);
            newReservation.Room = RoomsService.Instance.GetRoom(model.RoomID);
            ReservationService.Instance.SaveReservation(newReservation);
            RoomsService.Instance.UpdateVacantByandVacany(model.RoomID, newReservation.VacantBy);
            return RedirectToAction("MasterReservationTable");
        }




        public ActionResult MasterReservationTable(ReservationSearchViewModel model)
        {
            
            model.Reservations = MasterReservationsService.Instance.GetMasterReservations();
            if (model != null)
            {
                return PartialView("MasterReservationTable", model);
            }
            else
            {
                return HttpNotFound();
            }

        }



        [HttpGet]
        public ActionResult Edit(int ID)
        {
            CheckRole();
            if (role == false)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                EditReservationViewModel model = new EditReservationViewModel();
                var masterreservation = MasterReservationsService.Instance.GetMasterReservation(ID);
                model.ID = masterreservation.ID;
                model.Rooms = RoomsService.Instance.GetAvailableRooms();
                model.RoomSpecification = masterreservation.RoomSpecification;
                model.ReservationAgenda = masterreservation.ReservationAgenda;
                model.ReservationTime = masterreservation.ReservationTime;
                model.VacantBy = masterreservation.VacantBy;
                model.BookedBy = masterreservation.BookedBy;
                if (masterreservation.Room.HaveWifi == false)
                {
                    ViewBag.havewifi = "No";
                }
                else
                {
                    ViewBag.havewifi = "Yes";
                }
                return PartialView(model);
            }
        }




        [HttpPost]
        public ActionResult Edit(EditReservationViewModel model)
        {
            CheckRole();
            if (role == false)
            {
                return RedirectToAction("Login", "Login");

            }
            else
            {
                var existingReservation = MasterReservationsService.Instance.GetMasterReservation(model.ID);

                RoomsService.Instance.RelaseUpdateVacantByandVacany(existingReservation.Room.ID); // Room Vacancy is setting to True (Previous Room)
                RoomsService.Instance.UpdateVacantByandVacany(model.RoomID, model.VacantBy); //Room Vacancy is setting to False (new Room)

               // var newroom = RoomsService.Instance.GetRoomWithSpecs(model.RoomID);
                MasterReservationsService.Instance.UpdateRoomInReservation(model.ID,model.RoomID); //Changing Room in Reservation

                existingReservation.ReservationAgenda = model.ReservationAgenda;
                existingReservation.ReservationTime = model.ReservationTime;
                int specsId = RoomsService.Instance.GetRoomSpecs(model.RoomID);
                existingReservation.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(specsId);
                existingReservation.VacantBy = model.VacantBy;
                existingReservation.BookedBy = model.BookedBy;
                MasterReservationsService.Instance.UpdateMasterReservation(existingReservation);
                return RedirectToAction("MasterReservationTable");

            }

        }




        [HttpPost]
        public ActionResult Delete(ReservationSearchViewModel model)
        {
            var existingReservation = ReservationService.Instance.GetReservationsWithRoom(model.ID);
            RoomsService.Instance.RelaseUpdateVacantByandVacany(existingReservation.Room.ID);

            MasterReservationsService.Instance.DeleteMasterReservation(existingReservation.ID);
            return RedirectToAction("MasterReservationTable");
        }



    }
}

ReservationSystem/Controllers/ReservationController.cs
using ReservationSystem.Database;
using ReservationSystem.Entities;
using ReservationSystem.Services;
using ReservationSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ReservationSystem.Controllers
{
    public class ReservationController : Controller
    {
        // GET: Reservation
        public ActionResult Index()
        {
            
            return View();
        }


        [HttpGet]
        public ActionResult Create(int ID)
        {
            NewReservationViewModel model = new NewReservationViewModel();
            model.Room = RoomsService.Instance.GetRoomWithSpecs(ID);
            if(model.Room.HaveWifi == false)
            {
                ViewBag.havewifi = "No";
            }
            else
            {
                ViewBag.havewifi = "Yes";
            }
            return PartialView(model.Room);

        }



        [HttpPost]
        public ActionResult Create(NewReservationViewModel model)
        {
            var newReservation = new Reservations();
            newReservation.ReservationTime = model.ReservationTime;
            newReservation.ReservationAgenda = model.ReservationAgenda;
            newReservation.BookedBy = model.BookedBy;
            newReservation.VacantBy = model.VacantBy;
            newReservation.MeetingStatus = "In Process";
            newReservation.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(model.RoomSpecificationID);
            newReservation.Room = RoomsService.Instance.GetRoom(model.RoomID);
            ReservationService.Instance.SaveReservation(newReservation);
            RoomsService.Instance.UpdateVacantByandVacany(model.RoomID, newReservation.VacantBy);
            return RedirectToAction("ReservationTable");
        }



        public JsonResult SendMailToUser(NewReservationViewModel r)
        {
            bool result = false;
            var roomname = RoomsService.Instance.GetRoomName(r.RoomID);
            var vacantby = r.VacantBy;
            var bookedby = r.BookedBy;
            var agenda = r.ReservationAgenda;
            var time = r.ReservationTime;
            result = SendEmail(Convert.ToString(Session["Email"]), "Reservation Booking", "<p> Hi,"+Session["FirstName"]+" Your Room Reservations is confirmed. In case of any assistance contact IT. <br /> <b>Room Name:</b>" + roomname + "<br /> <b>Vacant By:</b>" + vacantby + "<br /> <b>Booking By:</b>" + bookedby + "<br /><b>Agenda:</b>" + agenda + "<br /> <b>Booking Time:</b>" + time + "</p>");
            return Json(result, JsonRequestBehavior.AllowGet);

        }

        public bool SendEmail(string toEmail, string subject, string emailBody)
        {
            try
            {
                string senderEmail = System.Configuration.ConfigurationManager.AppSettings["smtpUserEmail"].ToString();
                string senderPassword = System.Configuration.ConfigurationManager.AppSettings["smtpPassword"].ToString();

                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.EnableSsl = true;
                client.Timeout = 100000;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(senderEmail, senderPassword);

                MailMessage mailMessage = new MailMessage(senderEmail, toEmail, subject, emailBody);
                mailMessage.IsBodyHtml = true;
                mailMessage.BodyEncoding = UTF8Encoding.UTF8;
                client.Send(mailMessage);

                return true;
            }
            catch (Exception ex)
            {

                return false;
            }

        }


        public ActionResult ReservationTable(ReservationSearchViewModel model)
        {
            model.Rooms = RoomsService.Instance.GetAvailableRooms();
            if (model.Rooms != null)
            {
                return PartialView("ReservationTable", model);
            }
            else
            {
                return HttpNotFound();
            }

        }


        [HttpGet]
        public ActionResult Edit(int ID)
        {

            EditReservationViewModel model = new EditReservationViewModel();
            var reservation = ReservationService.Instance.GetReservation(ID);
            model.ID = reservation.ID;
            model.ReservationAgenda = reservation.ReservationAgenda;
            model.ReservationTime = reservation.ReservationTime;
            model.MeetingStatus = reservation.MeetingStatus;
            model.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(model.RoomSpecification.ID);
            model.Room = RoomsService.Instance.GetRoom(model.Room.ID);
            return PartialView(model);


        }

        [HttpPost]
        public ActionResult Edit(EditReservationViewModel model)
        {
            var existignReservation = ReservationService.Instance.GetReservation(model.ID);
            existignReservation.Room =  RoomsService.Instance.GetRoom(model.Room.ID);
            existignReservation.ReservationAgenda = model.ReservationAgenda;
            existignReservation.ReservationTime = model.ReservationTime;
            existignReservation.MeetingStatus = model.MeetingStatus;
            existignReservation.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(model.RoomSpecification.ID);
            ReservationService.Instance.UpdateReservation(existignReservation);
            return RedirectToAction("ReservationTable");

        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ReservationService.Instance.DeleteReservation(ID);
            return RedirectToAction("ReservationTable");
        }


        public List<Reservations> GetMyReservations()
        {
            var bookedby = Convert.ToString(Session["UserName"]);
            using (var context = new RBContext())
            {

                return context.Reservations.Include(x=>x.Room).Include(x=>x.RoomSpecification)
                    .Where(x => x.BookedBy == bookedby)
                    .ToList();

            }
        }


        public ActionResult ViewMyReservations(ReservationSearchViewModel model)
        {

            model.Reservations = GetMyReservations();
            if (model != null)
            {
                return PartialView("ViewMyReservations", model);
            }
            else
            {
                return HttpNotFound();
            }

        }


        [HttpPost]
        public ActionResult EndMeeting(int ID)
        {

            int roomid = ReservationService.Instance.GetRoomID(ID);
            RoomsService.Instance.RelaseUpdateVacantByandVacany(roomid);
            ReservationService.Instance.EndMeeting(ID);
            return RedirectToAction("ViewMyReservations");
        }


        public ActionResult MyReseservationIndex()
        {

            return View();
        }





    }
}

ReservationSystem/Views/MasterReservation/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<form class="forms-sample" id="createmasterreservation">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Book Reservation</h4>
                <input type="text" name="RoomID" hidden value="@Model.ID" />





                <input type="text" name="RoomSpecificationID" hidden value="@Model.RoomSpecification.ID" />


                <div class="form-group">
                    <label>Have Wifi:</label>
                    <input disabled type="text" id="HaveWifi" value="@ViewBag.havewifi" name="HaveWifi" />
                </div>
                <div class="form-group">

                    <label>Room Name:</label>
                    <input disabled type="text" id="Room" value="@Model.RoomName" name="HaveWifi" />
                </div>

                <div class="form-group">

                    <label>Enter Reservation Agenda</label>
                    <input type="text" class="form-control" id="ReservationAgenda" placeholder="Reservation Agenda" name="ReservationAgenda" />
                </div>

                <div class="form-group">

                    <label>Enter Reservation Date and Time</label>
                    <input type="datetime-local" id="ReservationTime" class="form-control" name="ReservationTime" />
                </div>

                <div class="form-group">

                    <input hidden type="text" class="form-control" id="BookedBy" value="@Session["UserName"]" name="BookedBy" />
                </div>

                <div class="form-group">

                    <label>Vacant By</label>
                    <input type="text" class="form-control" id="VacantBy" name="VacantBy" />
                </div>

                <button id="btnSave" type="button" class="btn btn-primary mr-2"> BOOK ROOM </button>
                <button id="btnCancel" type="button" class="btn btn-light">Cancel</button>
            </div>
        </div>
    </div>
</form>


<script>

    $("#btnCancel").click(function () {
        focusAction2();
        $("#createmasterreservation").html("")

    });

    function focusAction2() {
        $('html, body').animate({
            scrollTop: $("#reservationactioncontainer").offset().top - 100
        }, 1000);
    }



    $("#btnSave").click(function () {

        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "Reservation")',
            data: $("#createmasterreservation").serialize()

        })
            .done(function (response) {
                $("#masterreservationcontainer").html(response);
                $("#createmasterreservation").html("")
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {

            })

    });


</script>

ReservationSystem/Views/MasterReservation/Edit.cshtml
@model ReservationSystem.ViewModels.EditReservationViewModel

@{
    ViewBag.Title = "Edit";
}

<form class="forms-sample" id="updatemasterreservation">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Book Reservation</h4>
                <input type="text" name="ID" hidden value="@Model.ID" />

                <div class="form-group">
                    <label>Have Wifi:</label>
                    <input disabled type="text" id="HaveWifi" value="@ViewBag.havewifi" name="HaveWifi" />
                </div>


           <select id="RoomID" name="RoomID">
                @foreach (var room in Model.Rooms)
                {
                    <option value="@room.ID">@room.RoomName</option>
                }
           </select>



                <div class="form-group">

                    <label>Enter Reservation Agenda</label>
                    <input type="text" class="form-control" value="@Model.ReservationAgenda" id="ReservationAgenda" placeholder="Reservation Agenda" name="ReservationAgenda" />
                </div>

                <div class="form-group">

                    <label>Enter Reservation Date and Time</label>
                    <input type="datetime-local" id="ReservationTime" value="@Model.ReservationTime" class="form-control" name="ReservationTime" />
                </div>

                <div class="form-group">

                    <input hidden type="text" value="@Model.BookedBy" class="form-control" id="BookedBy" name="BookedBy" />
                </div>

                <div class="form-group">

                    <label>Vacant By</label>
                    
                    <input type="text" class="form-control" value="@Model.VacantBy" id="VacantBy" name="VacantBy" />
                </div>

                <button id="btnUpdate" type="button" class="btn btn-primary mr-2">UPDATE </button>
                <button id="btnCancel" type="button" class="btn btn-light">Cancel</button>
            </div>
        </div>
    </div>
</form>


<script>


     $("#btnUpdate").click(function () {

        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "MasterReservation")',
            data: $("#updatemasterreservation").serialize()

        })
            .done(function (response) {
                $("#masterreservationcontainer").html(response);
                $("#updatemasterreservation").html("")
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {

            })

    });



    $("#btnCancel").click(function () {
        focusAction2();
        $("#updatemasterreservation").html("")

    });

    function focusAction2() {
        $('html, body').animate({
            scrollTop: $("#masterreservationactioncontainer").offset().top - 100
        }, 1000);
    }


</script>

ReservationSystem/Views/MasterReservation/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Master Reservations</h2>
<button class="btn btn-primary mr-2" onclick="window.location.href = '@Url.Action("AdminDashboard","Login")';">BACK</button>
<div id="masterreservationcontainer">
    @{
        Html.RenderAction("MasterReservationTable");

    }
</div>
<br />
<div id="masterreservationactioncontainer">

</div>

ReservationSystem/Views/MasterReservation/MasterReservationTable.cshtml
@model ReservationSystem.ViewModels.ReservationSearchViewModel

@{ ViewBag.Title = "MasterReservationTable"; }

<div class="row">
    <div class="table-responsive">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <td>Room Name</td>
                    <td>Wifi</td>
                    <td>Room Location</td>
                        <td>Projection</td>
                    <td>Booked By</td>
                    <td>Vacant By</td>
                    <td>Reservation Time</td>
                    <td>Agenda</td>
                    <td>Status</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                @if (Model.Reservations.Count != 0)
                {
                    foreach (var reservation in Model.Reservations)
                    {
    <tr>
        <td>@reservation.Room.RoomName</td>
        @if(reservation.Room.HaveWifi == true)
                    {
            <td>Yes</td>
                    }
                    else
                    {
            <td>No</td>
                    }
        <td>@reservation.Room.RoomLocation</td>
        <td>@reservation.RoomSpecification.RoomProjectionSpecs</td>
        <td>@reservation.BookedBy</td>
        <td>@reservation.VacantBy</td>
        <td>@reservation.ReservationTime</td>
        <td>@reservation.ReservationAgenda</td>
        <td>@reservation.MeetingStatus</td>
        <td>
            <button type="button" class="btnEdit btn btn-icon-text mb-3 mb-sm-0 btn-inverse-warning font-weight-normal" data-id="@reservation.ID">EDIT</button>
            <button type="button" class="btnDelete btn btn-icon-text mb-3 mb-sm-0 btn-inverse-warning font-weight-normal" data-id="@reservation.ID">DELETE</button>
        </td>

    </tr>

                    }
                }
                else
                {
    <tr >
        <td class="text-danger" colspan="4"> No Reservation Found.</td>
    </tr>}
            </tbody>
        </table>

    </div>
</div>
<script>
    $(".btnEdit").click(function () {
        $.ajax({
                    url: '@Url.Action("Edit", "MasterReservation")',
            data: {
                        ID: $(this).attr('data-id')
            }

                    })
            .done(function (response) {
                $("#masterreservationactioncontainer").html(response);
                    })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("Fail");
                    })

    });



    $(".btnDelete").click(function () {
                    var confirmdelete = confirm("Are you sure want to delete?");
                    if (confirmdelete) {
            $.ajax({
                        type: 'POST',
                url: '@Url.Action("Delete", "MasterReservation")',
                data: {
                            ID: $(this).attr('data-id')

                }

                        })
                .done(function (response) {
                    $("#masterreservationcontainer").html(response);
                        })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                            alert("FAIL");
                        });
                    }

                });
</script>