ReservationSystem/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ReservationSystem.ViewModels
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}

ReservationSystem/Controllers/ReservationController.cs
using ReservationSystem.Database;
using ReservationSystem.Entities;
using ReservationSystem.Services;
using ReservationSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ReservationSystem.Controllers
{
    public class ReservationController : Controller
    {
        // GET: Reservation
        public ActionResult Index()
        {
            
            return View();
        }


        [HttpGet]
        public ActionResult Create(int ID)
        {
            NewReservationViewModel model = new NewReservationViewModel();
            model.Room = RoomsService.Instance.GetRoomWithSpecs(ID);
            if(model.Room.HaveWifi == false)
            {
                ViewBag.havewifi = "No";
            }
            else
            {
                ViewBag.havewifi = "Yes";
            }
            return PartialView(model.Room);

        }



        [HttpPost]
        public ActionResult Create(NewReservationViewModel model)
        {
            var newReservation = new Reservations();
            newReservation.ReservationTime = model.ReservationTime;
            newReservation.ReservationAgenda = model.ReservationAgenda;
            newReservation.BookedBy = model.BookedBy;
            newReservation.VacantBy = model.VacantBy;
            newReservation.MeetingStatus = "In Process";
            newReservation.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(model.RoomSpecificationID);
            newReservation.Room = RoomsService.Instance.GetRoom(model.RoomID);
            ReservationService.Instance.SaveReservation(newReservation);
            RoomsService.Instance.UpdateVacantByandVacany(model.RoomID, newReservation.VacantBy);
            return RedirectToAction("ReservationTable");
        }



        public JsonResult SendMailToUser(NewReservationViewModel r)
        {
            bool result = false;
            var roomname = RoomsService.Instance.GetRoomName(r.RoomID);
            var vacantby = r.VacantBy;
            var bookedby = r.BookedBy;
            var agenda = r.ReservationAgenda;
            var time = r.ReservationTime;
            result = SendEmail(Convert.ToString(Session["Email"]), "Reservation Booking", "<p> Hi,"+Session["FirstName"]+" Your Room Reservations is confirmed. In case of any assistance contact IT. <br /> <b>Room Name:</b>" + roomname + "<br /> <b>Vacant By:</b>" + vacantby + "<br /> <b>Booking By:</b>" + bookedby + "<br /><b>Agenda:</b>" + agenda + "<br /> <b>Booking Time:</b>" + time + "</p>");
            return Json(result, JsonRequestBehavior.AllowGet);

        }

        public bool SendEmail(string toEmail, string subject, string emailBody)
        {
            try
            {
                string senderEmail = System.Configuration.ConfigurationManager.AppSettings["smtpUserEmail"].ToString();
                string senderPassword = System.Configuration.ConfigurationManager.AppSettings["smtpPassword"].ToString();

                SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
                client.EnableSsl = true;
                client.Timeout = 100000;
                client.DeliveryMethod = SmtpDeliveryMethod.Network;
                client.UseDefaultCredentials = false;
                client.Credentials = new NetworkCredential(senderEmail, senderPassword);

                MailMessage mailMessage = new MailMessage(senderEmail, toEmail, subject, emailBody);
                mailMessage.IsBodyHtml = true;
                mailMessage.BodyEncoding = UTF8Encoding.UTF8;
                client.Send(mailMessage);

                return true;
            }
            catch (Exception ex)
            {

                return false;
            }

        }


        public ActionResult ReservationTable(ReservationSearchViewModel model)
        {
            model.Rooms = RoomsService.Instance.GetAvailableRooms();
            if (model.Rooms != null)
            {
                return PartialView("ReservationTable", model);
            }
            else
            {
                return HttpNotFound();
            }

        }


        [HttpGet]
        public ActionResult Edit(int ID)
        {

            EditReservationViewModel model = new EditReservationViewModel();
            var reservation = ReservationService.Instance.GetReservation(ID);
            model.ID = reservation.ID;
            model.ReservationAgenda = reservation.ReservationAgenda;
            model.ReservationTime = reservation.ReservationTime;
            model.MeetingStatus = reservation.MeetingStatus;
            model.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(model.RoomSpecification.ID);
            model.Room = RoomsService.Instance.GetRoom(model.Room.ID);
            return PartialView(model);


        }

        [HttpPost]
        public ActionResult Edit(EditReservationViewModel model)
        {
            var existignReservation = ReservationService.Instance.GetReservation(model.ID);
            existignReservation.Room =  RoomsService.Instance.GetRoom(model.Room.ID);
            existignReservation.ReservationAgenda = model.ReservationAgenda;
            existignReservation.ReservationTime = model.ReservationTime;
            existignReservation.MeetingStatus = model.MeetingStatus;
            existignReservation.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(model.RoomSpecification.ID);
            ReservationService.Instance.UpdateReservation(existignReservation);
            return RedirectToAction("ReservationTable");

        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ReservationService.Instance.DeleteReservation(ID);
            return RedirectToAction("ReservationTable");
        }


        public List<Reservations> GetMyReservations()
        {
            var bookedby = Convert.ToString(Session["UserName"]);
            using (var context = new RBContext())
            {

                return context.Reservations.Include(x=>x.Room).Include(x=>x.RoomSpecification)
                    .Where(x => x.BookedBy == bookedby)
                    .ToList();

            }
        }


        public ActionResult ViewMyReservations(ReservationSearchViewModel model)
        {

            model.Reservations = GetMyReservations();
            if (model != null)
            {
                return PartialView("ViewMyReservations", model);
            }
            else
            {
                return HttpNotFound();
            }

        }


        [HttpPost]
        public ActionResult EndMeeting(int ID)
        {

            int roomid = ReservationService.Instance.GetRoomID(ID);
            RoomsService.Instance.RelaseUpdateVacantByandVacany(roomid);
            ReservationService.Instance.EndMeeting(ID);
            return RedirectToAction("ViewMyReservations");
        }


        public ActionResult MyReseservationIndex()
        {

            return View();
        }





    }
}

ReservationSystem/Controllers/RoomController.cs
using ReservationSystem.Entities;
using ReservationSystem.Services;
using ReservationSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReservationSystem.Controllers
{
    public class RoomController : Controller
    {
        // GET: Room
        bool role = false;
        public void CheckRole()
        {
            role = false;
            if (Session["UserName"] == null)
            {
                role = false;
            }
            string[] roles = System.Web.Security.Roles.GetRolesForUser(Convert.ToString(Session["UserName"]));
            if (roles[0] == "Admin")
            {
                role = true;

            }
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            CheckRole();

            if (role == false)
            {
                return RedirectToAction("Login", "Login");

            }
            else
            {
                var roomspecs = RoomSpecificationService.Instance.GetRoomSpecifications();
                return PartialView(roomspecs);
            }
        }

        [HttpPost]
        public ActionResult Create(NewRoomViewModel model)
        {
            CheckRole();
            if (role == false)
            {
                return RedirectToAction("Login", "Login");

            }
            else
            {
                var newRoom = new Room();
                newRoom.RoomName = model.RoomName;
                newRoom.RoomLocation = model.RoomLocation;
                newRoom.HaveWifi = model.HaveWifi;
                newRoom.Vacant = model.Vacant;
                newRoom.VacantBy = model.VacantBy;
                newRoom.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(model.RoomSpecificationID);
                RoomsService.Instance.SaveRoom(newRoom);
                return RedirectToAction("RoomsTable");
            }
        }

        public ActionResult RoomsTable(string search)
        {
            CheckRole();

            if (role == false)
            {
                return View("Login", "Login");

            }
            else
            {
                RoomSearchViewModel model = new RoomSearchViewModel();
                //if has value     //then values                    : else 1;   
                model.SearchTerm = search;
                model.Room = RoomsService.Instance.GetRooms(search);
                if (model.Room != null)
                {
                    return PartialView("RoomsTable", model);
                }
                else
                {
                    return HttpNotFound();
                }
            }
        }



        [HttpGet]
        public ActionResult Edit(int ID)
        {
            CheckRole();

            if (role == false)
            {
                return RedirectToAction("Login", "Login");

            }
            else
            {
                EditRoomViewModel model = new EditRoomViewModel();
                var room = RoomsService.Instance.GetRoom(ID);
                model.ID = room.ID;
                model.RoomName = room.RoomName;
                model.VacantBy = room.VacantBy;
                model.RoomLocation = room.RoomLocation;
                model.HaveWifi = room.HaveWifi;
                model.Vacant = room.Vacant;
                model.RoomSpecifications = RoomSpecificationService.Instance.GetRoomSpecifications();

                return PartialView(model);
            }

        }

        [HttpPost]
        public ActionResult Edit(EditRoomViewModel model)
        {            CheckRole();

            if (role == false)
            {
                return RedirectToAction("Login", "Login");

            }
            else
            {
                var existingProduct = RoomsService.Instance.GetRoom(model.ID);
                existingProduct.RoomName = model.RoomName;
                existingProduct.VacantBy = model.VacantBy;
                existingProduct.Vacant = model.Vacant;
                existingProduct.RoomLocation = model.RoomLocation;
                existingProduct.RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(model.RoomSpecificationID);
                existingProduct.HaveWifi = model.HaveWifi;
                RoomsService.Instance.UpdateRoom(existingProduct);
                return RedirectToAction("RoomsTable");
            }
        }

        [HttpPost]
        public ActionResult Delete(int ID)
        {
            RoomsService.Instance.DeleteRoom(ID);
            return RedirectToAction("RoomsTable");
        }

    }
}

ReservationSystem/Controllers/RoomSpecificationController.cs
using ReservationSystem.Entities;
using ReservationSystem.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReservationSystem.Controllers
{
    public class RoomSpecificationController : Controller
    {
        // GET: RoomSpecification
        bool role = false;
        public void CheckRole()
        {
             role = false;
            if (Session["UserName"] == null)
            {
                role = false;
            }
            string[] roles = System.Web.Security.Roles.GetRolesForUser(Convert.ToString(Session["UserName"]));
            if (roles[0] == "Admin")
            {
                role = true;

            }
        }

        public ActionResult RoomSpecificationTable()
        {
            CheckRole();
            if (role == false)
            {
                return RedirectToAction("Login", "Login");
            }

            else
            {
                var roomspecs = RoomSpecificationService.Instance.GetRoomSpecifications();
                return PartialView(roomspecs);
            }
        }


        [HttpGet]
        public ActionResult Index()
        {
            CheckRole();
            if(role == false)
            { 
                return RedirectToAction("Login", "Login");

            }
            else
            {
                return View();

            }
        }


        [HttpGet]
        public ActionResult Create()
        {
            CheckRole();
            if (role == false)
            {
                return RedirectToAction("Login", "Login");

            }
            else
            {
                return PartialView();
            }

        }

        [HttpPost]
        public ActionResult Create(RoomSpecification roomSpecification)
        {
            CheckRole();
            if (role == false)
            {
                return RedirectToAction("Login", "Login");

            }
            else
            {
                RoomSpecificationService.Instance.SaveRoomSpecification(roomSpecification);
                return RedirectToAction("RoomSpecificationTable");
            }
        }


        [HttpGet]
        public ActionResult Edit(int ID)
        {
            CheckRole();
            if (role == false)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {

                var RoomSpecification = RoomSpecificationService.Instance.GetRoomSpecification(ID);
                return PartialView(RoomSpecification);
            }
        }

        [HttpPost]
        public ActionResult Edit(RoomSpecification roomSpecification)
        {   CheckRole();
            if (role == false)
            {
                return RedirectToAction("Login", "Login");

            }
            else
            {
                RoomSpecificationService.Instance.UpdateRoomSpecification(roomSpecification);
                return RedirectToAction("RoomSpecificationTable");
            }
      
        }



        [HttpPost]
        public ActionResult Delete(int ID)
        {
            RoomSpecificationService.Instance.DeleteRoomSpecification(ID);
            return RedirectToAction("RoomSpecificationTable");
        }


    }
}

ReservationSystem/Views/Login/AdminDashboard.cshtml
@{
    ViewBag.Title = "AdminDashboard";
}

<body>
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="card-title">Admin Dashboard</h4>
                        <table class="table table-condensed">
                            <tr>
                                <td colspan="2">
                                    <button  onclick="window.location.href = '@Url.Action("Index","MasterReservation")';" class="btn btn-dark btn-block btn-icon-text col-md-12">
                                        <i class="mdi  btn-icon-prepend mdi-36px"></i>
                                        <span class="d-inline-block text-left">
                                            Manage Reservations
                                        </span>
                                    </button>
                                </td>
                                <td colspan="2">
                                    <button onclick="window.location.href = '@Url.Action("Index","User")';" class="btn btn-dark btn-block btn-icon-text col-md-12">
                                        <i class="mdi  btn-icon-prepend mdi-36px"></i>
                                        <span class="d-inline-block text-left">
                                            Users
                                        </span>
                                    </button>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <button onclick="window.location.href = '@Url.Action("Index","Room")';" class="btn btn-dark btn-block btn-icon-text col-md-12">
                                        <i class="mdi  btn-icon-prepend mdi-36px"></i>
                                        <span class="d-inline-block text-left">
                                            Rooms
                                        </span>
                                    </button>
                                </td>
                                <td colspan="2">
                                    <button onclick="window.location.href = '@Url.Action("Index","RoomSpecification")';" class="btn btn-dark btn-block btn-icon-text col-md-12">
                                        <i class="mdi  btn-icon-prepend mdi-36px"></i>
                                        <span class="d-inline-block text-left">
                                            Rooms Specification
                                        </span>
                                    </button>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="4">
                                    <button onclick="window.location.href = '@Url.Action("Login","Login")';" class="btn btn-dark btn-block btn-icon-text col-md-12">
                                        <i class="mdi  btn-icon-prepend mdi-36px"></i>
                                        <span class="d-inline-block text-left">
                                            Log Out
                                        </span>
                                    </button>
                                </td>
                            </tr>

                        </table>
                           
                        </div>
                    </div>
            </div>
        </div>
    </div>

</body>

ReservationSystem/Views/Login/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = null;
}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V1</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Content/LoginTemplate/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/LoginTemplate/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/LoginTemplate/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/LoginTemplate/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/LoginTemplate/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/LoginTemplate/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/LoginTemplate/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/LoginTemplate/css/main.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="~/Content/LoginTemplate/images/img-01.png" alt="IMG">
                </div>
                @using (Html.BeginForm("Login", "Login", FormMethod.Post, new { @class = "login100-form validate-form" }))
                {
                    <span class="login100-form-title">
                        Member Login
                    </span>
                    <h4 class="text-danger">@ViewBag.ErrorMessage</h4>
                    <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                        <input class="input100" id="Email" type="text" name="Email" placeholder="Email">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </span>
                    </div>


                    <div class="wrap-input100 validate-input" data-validate="Password is required">
                        <input class="input100" id="Password" type="password" name="Password" placeholder="Password">
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <i class="fa fa-lock" aria-hidden="true"></i>
                        </span>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </div>

                   


                    <div class="text-center p-t-136">
                        <a class="txt2" href="@Url.Action("Register","Login")">
                            Create your Account
                            <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>



    <!--===============================================================================================-->
    <script src="~/Content/LoginTemplate/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/LoginTemplate/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Content/LoginTemplate/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/LoginTemplate/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Content/LoginTemplate/vendor/tilt/tilt.jquery.min.js"></script>
    <script>
        $('.js-tilt').tilt({
            scale: 1.1
        })
    </script>
    <!--===============================================================================================-->
    <script src="~/Content/LoginTemplate/js/main.js"></script>

</body>
</html>

ReservationSystem/Views/Login/UserDashboard.cshtml
@{
    ViewBag.Title = "UserDashboard";
}



<body>
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="card-title">User Dashboard</h4>
                        <table class="table table-condensed">
                            <tr>
                                <td colspan="2">
                                    <button onclick="window.location.href = '@Url.Action("Index","Reservation")';" class="btn btn-block btn-dark btn-icon-text">
                                        <i class="mdi mdi-apple btn-icon-prepend mdi-36px"></i>
                                        <span class="d-inline-block text-left">
                                            Make Reservation
                                        </span>
                                    </button>
                                </td>
                                <td colspan="2">
                                    <button onclick="window.location.href = '@Url.Action("Index","User")';" class="btn btn-block btn-dark btn-icon-text">
                                        <i class="mdi mdi-android-debug-bridge btn-icon-prepend mdi-36px"></i>
                                        <span class="d-inline-block text-left">
                                            User Settings
                                        </span>
                                    </button>
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    <button onclick="window.location.href = '@Url.Action("MyReseservationIndex","Reservation")';" class="btn btn-block btn-dark btn-icon-text">
                                        <i class="mdi mdi-android-debug-bridge btn-icon-prepend mdi-36px"></i>
                                        <span class="d-inline-block text-left">
                                            View My Reservations
                                        </span>
                                    </button>
                                </td>
                                <td colspan="2">
                                    <button onclick="window.location.href = '@Url.Action("Login","Login")';" class="btn btn-block btn-dark btn-icon-text">
                                        <i class="mdi mdi-android-debug-bridge btn-icon-prepend mdi-36px"></i>
                                        <span class="d-inline-block text-left">
                                            Log Out
                                        </span>
                                    </button>
                                </td>
                            </tr>
                           
                        </table>

                    </div>
                </div>
            </div>
        </div>
    </div>

</body>